include: package:flutter_lints/flutter.yaml

linter:
  # Below, you can customize linting rules for this project. You may choose to
  # disable specific rules from the `package:flutter_lints/flutter.yaml`
  # configuration or add new ones. A comprehensive list of available lints
  # with documentation can be found at https://dart.dev/lints.
  #
  # If you wish to suppress a linting rule for a particular section of code,
  # you can use the syntax `// ignore: rule_name` for a single line or
  # `// ignore_for_file: rule_name` for an entire file where the issue occurs.
  rules:
  # Uncomment the following line to disable the `avoid_print` rule:
  # avoid_print: false
  # Uncomment the following line to enforce single quotes instead of double quotes:
  # prefer_single_quotes: true
