name: news_app
description: "My news app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.6.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  logger: ^1.2.0
  url_launcher: ^6.1.6
  provider: ^6.0.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
